### ISSUE TITLE
Use fontSize from config

### ISSUE THREAD

**Issue by ekmartin** [henrikdahl/hyperterm-chesterish#1]
Hey! This is a beautiful theme. Would be really nice if it didn't override the `fontSize` already set though.

**Comment by henrikruscon** [comment]
Hey!  @ekmartin

I agree. I'm not sure why I was overriding it in the first place, I must have been tired, for some reason I was thinking the theme wouldn't work with a different `fontSize`. 🙃

Fixed with a commit. Thanks for your support! 👊

**Comment by ekmartin** [comment]
Great, thanks!
