### ISSUE TITLE
Multiple packages

### ISSUE THREAD

**Issue by ekmartin** [henrikdahl/hyperterm-chesterish#2]
Maybe it would be smart to separate out the footer into its own package? You could still keep the styling here, but that way you wouldn't need to duplicate the code in your other themes (such as hyperterm-base16-ocean-saturated), and people could use your themes without having to use the footer.

**Comment by henrikruscon** [comment]
@ekmartin 

I agree. I commented this on `hyperterm-base16-ocean-saturated`.

I would personally prefer the theme to have a config with options such as hiding the footer. Haven't had time to look into how it's done. I might just separate it out into its own package. Thanks for bringing it forth!

Right now you could simply add `css: '.footer_footer { display: none !important; }',` to your config in `.hyperterm.js`. ✌️

**Comment by henrikruscon** [comment]
Sorry for the delay, been swamped with work. Removed the status line from the theme. Adding it as its own separate plugin soon, just need to recode it as it currently doesn't work with the latest version of HyperTerm. ✌️

**Comment by henrikruscon** [comment]
@ekmartin 

It's now it's own plugin and it works with other themes than mine.
https://github.com/henrikdahl/hyper-statusline

👋

**Comment by ekmartin** [comment]
No worries - great work!
