### ISSUE TITLE
Tabs not clickable on Linux

### ISSUE THREAD

**Issue by drschwabe** [henrikdahl/hyperterm-chesterish#3]
This might be specific to any theme that hides the shell, but just wanted to point out that tabs are broken / not clickable in this theme (on my setup, Ubuntu 16).    They display and look fine and you can create new tabs but when you click on them the window tries to drag instead of the intended action of switching to the clicked tab.

**Comment by henrikruscon** [comment]
I'm thinking this is probably an issue with electron itself. I'll look into it, maybe the solution is to not enforce a hidden header.

I've been thinking about having a config for the theme itself so that you can decide, either that or separate them into individual plugins.

**Comment by drschwabe** [comment]
As a quick fix maybe there is a way to check the platform in your logic and if linux show header. 

Config would be a nice idea.  On a related note, it would be cool if hyperterm made it easy for plugin authors to accept a default config object; ie- in .hyperterm.js 

```
plugins: [
  'hyperterm-blink', 
  'hyperterm-tabs', 
  { name: 'hyperterm-chesterish',
    config: { showHeader: true }
  }, 
   'hyperpower'
]
```

**Comment by henrikruscon** [comment]
Sorry for the delay, got a lot of work 😁

Started working on a version that includes a config setup. 👋

That way you can override features specific to the theme such as blinking cursor caret, tab icons. They will all default to enabled (true).

I'm wondering which version of the visible header to go with. Transparent or not?

Non transparent:
![visible](https://cloud.githubusercontent.com/assets/1430576/18524924/d8603fba-7aba-11e6-8f50-bc5bf758fc6c.png)

Transparent:
![transparent](https://cloud.githubusercontent.com/assets/1430576/18524931/deb86c70-7aba-11e6-8cf6-21f954a05e35.png)

**Comment by drschwabe** [comment]
Well, maybe header style should be a config option too :)

**Comment by henrikruscon** [comment]
Sorry for leaving this for so long. If you're still using my theme, is this still an issue in latest version of Hyper? @drschwabe 👋
