### ISSUE TITLE
Additional windows difficult to close

### ISSUE THREAD

**Issue by robertkern** [henrikdahl/hyperterm-chesterish#6]
The red/yellow/green buttons are removed in this theme which makes it difficult to close a window. If I have multiple windows open with multiple tabs in each, when i want to close one of the windows i have to use shift-cmd-W or go to the Shell menu and select Close Window.

I like how the app looks with your theme (and without the red/yellow/green buttons), but wondering if there could be an easier way to close windows?

**Comment by robertkern** [comment]
Actually sorry it's the `hyper-tabs-enhanced` plugin

**Comment by henrikruscon** [comment]
With `hyper-tabs-enhanced` plugin you can also add custom traffic buttons with a config option.

![3578212a-def9-11e6-9e97-6d635bb89db8](https://cloud.githubusercontent.com/assets/1430576/22802872/d65028ee-ef12-11e6-8998-bcfdb38ad32c.png)

```javascript
module.exports = {
  config: {
    ...
      hyperTabs: {
        trafficButtons: true,
      }
    ...
  }
}
```

**Comment by robertkern** [comment]
Thank you, I have done that now :-)
